-- Telegram linking, notification preferences and service-role-only bot state.

create table if not exists public.telegram_link_codes (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  code text not null unique,
  expires_at timestamptz not null,
  created_at timestamptz not null default now()
);
create index if not exists telegram_link_codes_expiry_idx on public.telegram_link_codes(expires_at);

create table if not exists public.telegram_accounts (
  user_id uuid primary key references auth.users(id) on delete cascade,
  telegram_chat_id text not null unique,
  username text,
  first_name text,
  created_at timestamptz not null default now()
);

create table if not exists public.telegram_preferences (
  user_id uuid primary key references auth.users(id) on delete cascade,
  notifications_enabled boolean not null default true,
  credit_reminders boolean not null default true,
  recurring_reminders boolean not null default true,
  budget_alerts boolean not null default true,
  weekly_digest boolean not null default true,
  reminder_days integer[] not null default array[3,1,0],
  timezone text not null default 'UTC',
  updated_at timestamptz not null default now(),
  constraint telegram_reminder_days_valid check (
    cardinality(reminder_days) between 1 and 5 and reminder_days <@ array[0,1,2,3,5,7]
  )
);

create table if not exists public.telegram_pending_operations (
  token text primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  telegram_chat_id text not null,
  draft jsonb not null,
  expires_at timestamptz not null,
  created_at timestamptz not null default now()
);
create index if not exists telegram_pending_operations_expiry_idx
  on public.telegram_pending_operations(expires_at);

create table if not exists public.telegram_operations (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  telegram_chat_id text not null,
  operation_client_id text not null,
  amount numeric(14,2) not null,
  category text not null,
  note text not null default '',
  operation_date date not null,
  created_at timestamptz not null default now(),
  unique (user_id, operation_client_id)
);
create index if not exists telegram_operations_latest_idx
  on public.telegram_operations(user_id, created_at desc);

create table if not exists public.telegram_webhook_updates (
  update_id bigint primary key,
  created_at timestamptz not null default now()
);
create table if not exists public.telegram_rate_limits (
  telegram_chat_id text primary key,
  window_started_at timestamptz not null default now(),
  message_count integer not null default 0
);
create table if not exists public.telegram_notification_claims (
  user_id uuid not null references auth.users(id) on delete cascade,
  event_key text not null,
  state text not null default 'processing' check (state in ('processing','sent')),
  locked_until timestamptz not null default (now() + interval '5 minutes'),
  sent_at timestamptz,
  primary key (user_id, event_key)
);

-- The browser can only create/read/delete its own one-time link code.
alter table public.telegram_link_codes enable row level security;
drop policy if exists telegram_link_codes_owner_select on public.telegram_link_codes;
create policy telegram_link_codes_owner_select on public.telegram_link_codes
  for select to authenticated using (auth.uid() = user_id);
drop policy if exists telegram_link_codes_owner_insert on public.telegram_link_codes;
create policy telegram_link_codes_owner_insert on public.telegram_link_codes
  for insert to authenticated with check (auth.uid() = user_id);
drop policy if exists telegram_link_codes_owner_delete on public.telegram_link_codes;
create policy telegram_link_codes_owner_delete on public.telegram_link_codes
  for delete to authenticated using (auth.uid() = user_id);
grant select, insert, delete on public.telegram_link_codes to authenticated;

alter table public.telegram_accounts enable row level security;
alter table public.telegram_preferences enable row level security;
alter table public.telegram_pending_operations enable row level security;
alter table public.telegram_operations enable row level security;
alter table public.telegram_webhook_updates enable row level security;
alter table public.telegram_rate_limits enable row level security;
alter table public.telegram_notification_claims enable row level security;
-- A user may see the link status and remove their own account, but cannot set a
-- different user's chat id or alter service-managed identity fields.
drop policy if exists telegram_accounts_owner_select on public.telegram_accounts;
create policy telegram_accounts_owner_select on public.telegram_accounts
  for select to authenticated using (auth.uid() = user_id);
drop policy if exists telegram_accounts_owner_delete on public.telegram_accounts;
create policy telegram_accounts_owner_delete on public.telegram_accounts
  for delete to authenticated using (auth.uid() = user_id);

drop policy if exists telegram_preferences_owner_select on public.telegram_preferences;
create policy telegram_preferences_owner_select on public.telegram_preferences
  for select to authenticated using (auth.uid() = user_id);
drop policy if exists telegram_preferences_owner_insert on public.telegram_preferences;
create policy telegram_preferences_owner_insert on public.telegram_preferences
  for insert to authenticated with check (auth.uid() = user_id);
drop policy if exists telegram_preferences_owner_update on public.telegram_preferences;
create policy telegram_preferences_owner_update on public.telegram_preferences
  for update to authenticated using (auth.uid() = user_id) with check (auth.uid() = user_id);
grant select, delete on public.telegram_accounts to authenticated;
grant select, insert, update on public.telegram_preferences to authenticated;

-- State and chat identifiers are never exposed to anon/authenticated clients.
revoke all on public.telegram_pending_operations, public.telegram_operations,
  public.telegram_webhook_updates, public.telegram_rate_limits,
  public.telegram_notification_claims from anon, authenticated;
grant all on public.telegram_pending_operations, public.telegram_operations,
  public.telegram_webhook_updates, public.telegram_rate_limits,
  public.telegram_notification_claims, public.telegram_accounts,
  public.telegram_preferences, public.telegram_link_codes to service_role;

create or replace function public.consume_telegram_link_code(p_code text)
returns uuid language plpgsql security definer set search_path = '' as $$
declare v_user_id uuid;
begin
  delete from public.telegram_link_codes
   where upper(code) = upper(trim(p_code)) and expires_at > now()
   returning user_id into v_user_id;
  return v_user_id;
end;
$$;
revoke all on function public.consume_telegram_link_code(text) from public, anon, authenticated;
grant execute on function public.consume_telegram_link_code(text) to service_role;

create or replace function public.consume_telegram_pending(p_token text, p_chat_id text)
returns jsonb language plpgsql security definer set search_path = '' as $$
declare v_draft jsonb;
begin
  delete from public.telegram_pending_operations
   where token = p_token and telegram_chat_id = p_chat_id and expires_at > now()
   returning draft into v_draft;
  return v_draft;
end;
$$;
revoke all on function public.consume_telegram_pending(text,text) from public, anon, authenticated;
grant execute on function public.consume_telegram_pending(text,text) to service_role;

create or replace function public.claim_telegram_notification(p_user_id uuid, p_event_key text)
returns boolean language plpgsql security definer set search_path = '' as $$
declare v_claimed boolean := false;
begin
  insert into public.telegram_notification_claims(user_id, event_key, state, locked_until)
  values (p_user_id, p_event_key, 'processing', now() + interval '5 minutes')
  on conflict (user_id, event_key) do update
    set state = 'processing', locked_until = now() + interval '5 minutes'
    where telegram_notification_claims.state <> 'sent'
      and telegram_notification_claims.locked_until < now()
  returning true into v_claimed;
  return coalesce(v_claimed, false);
end;
$$;
revoke all on function public.claim_telegram_notification(uuid,text) from public, anon, authenticated;
grant execute on function public.claim_telegram_notification(uuid,text) to service_role;

create or replace function public.mark_telegram_notification_sent(p_user_id uuid, p_event_key text)
returns void language sql security definer set search_path = '' as $$
  update public.telegram_notification_claims
     set state = 'sent', sent_at = now(), locked_until = 'infinity'
   where user_id = p_user_id and event_key = p_event_key;
$$;
revoke all on function public.mark_telegram_notification_sent(uuid,text) from public, anon, authenticated;
grant execute on function public.mark_telegram_notification_sent(uuid,text) to service_role;

create or replace function public.release_telegram_notification(p_user_id uuid, p_event_key text)
returns void language sql security definer set search_path = '' as $$
  delete from public.telegram_notification_claims
   where user_id = p_user_id and event_key = p_event_key and state = 'processing';
$$;
revoke all on function public.release_telegram_notification(uuid,text) from public, anon, authenticated;
grant execute on function public.release_telegram_notification(uuid,text) to service_role;

create or replace function public.finalize_telegram_operation(p_token text, p_chat_id text)
returns jsonb language plpgsql security definer set search_path = '' as $$
declare
  v_pending public.telegram_pending_operations%rowtype;
  v_client_id text;
  v_op public.finance_operations%rowtype;
  v_amount numeric(14,2);
  v_type text;
begin
  select * into v_pending from public.telegram_pending_operations
   where token = p_token and telegram_chat_id = p_chat_id and expires_at > now()
   for update;
  if not found then return null; end if;
  v_amount := (v_pending.draft->>'amount')::numeric;
  v_type := v_pending.draft->>'type';
  if v_amount <= 0 or v_amount > 1000000000 or v_type not in ('income','expense') then
    raise exception 'Invalid pending operation';
  end if;
  v_client_id := 'tg-' || p_token;
  insert into public.finance_operations(user_id, client_id, type, amount, category, note, date)
  values (v_pending.user_id, v_client_id, v_type, v_amount,
          left(coalesce(v_pending.draft->>'category','Другое'), 80),
          left(coalesce(v_pending.draft->>'note','Операция из Telegram'), 300),
          (v_pending.draft->>'date')::date)
  on conflict (user_id, client_id) do nothing
  returning * into v_op;
  if not found then
    select * into v_op from public.finance_operations
     where user_id = v_pending.user_id and client_id = v_client_id;
  end if;
  insert into public.telegram_operations(user_id, telegram_chat_id, operation_client_id, amount, category, note, operation_date)
  values (v_pending.user_id, p_chat_id, v_client_id, v_amount,
          left(coalesce(v_pending.draft->>'category','Другое'), 80),
          left(coalesce(v_pending.draft->>'note','Операция из Telegram'), 300),
          (v_pending.draft->>'date')::date)
  on conflict (user_id, operation_client_id) do nothing;
  delete from public.telegram_pending_operations where token = p_token;
  return jsonb_build_object('client_id',v_op.client_id,'type',v_op.type,'amount',v_op.amount,
    'category',v_op.category,'note',v_op.note,'date',v_op.date);
end;
$$;
revoke all on function public.finalize_telegram_operation(text,text) from public, anon, authenticated;
grant execute on function public.finalize_telegram_operation(text,text) to service_role;

create or replace function public.undo_telegram_operation(p_operation_id bigint, p_chat_id text)
returns boolean language plpgsql security definer set search_path = '' as $$
declare v_operation public.telegram_operations%rowtype; v_deleted integer;
begin
  select * into v_operation from public.telegram_operations
   where id = p_operation_id and telegram_chat_id = p_chat_id
     and created_at > now() - interval '24 hours'
   for update;
  if not found then return false; end if;
  delete from public.finance_operations
   where user_id = v_operation.user_id and client_id = v_operation.operation_client_id;
  get diagnostics v_deleted = row_count;
  if v_deleted = 0 then return false; end if;
  delete from public.telegram_operations where id = p_operation_id;
  return true;
end;
$$;
revoke all on function public.undo_telegram_operation(bigint,text) from public, anon, authenticated;
grant execute on function public.undo_telegram_operation(bigint,text) to service_role;

create or replace function public.set_telegram_budget(p_user_id uuid, p_category text, p_amount numeric, p_period text default 'monthly')
returns void language plpgsql security definer set search_path = '' as $$
begin
  if p_category is null or length(trim(p_category)) = 0 or length(p_category) > 80
     or p_amount is null or p_amount < 0 or p_amount > 1000000000
     or p_period not in ('monthly','weekly') then
    raise exception 'Invalid budget';
  end if;
  insert into public.finance_profiles(user_id) values (p_user_id) on conflict (user_id) do nothing;
  if p_period = 'monthly' then
    if p_amount = 0 then
      update public.finance_profiles set budgets = coalesce(budgets,'{}'::jsonb) - p_category, updated_at=now() where user_id=p_user_id;
    else
      update public.finance_profiles set budgets = jsonb_set(coalesce(budgets,'{}'::jsonb), array[p_category], to_jsonb(round(p_amount,2)), true), updated_at=now() where user_id=p_user_id;
    end if;
  else
    if p_amount = 0 then
      update public.finance_profiles set settings = jsonb_set(coalesce(settings,'{}'::jsonb), '{weeklyBudgets}', coalesce(settings->'weeklyBudgets','{}'::jsonb) - p_category, true), updated_at=now() where user_id=p_user_id;
    else
      update public.finance_profiles set settings = jsonb_set(
        coalesce(settings,'{}'::jsonb), '{weeklyBudgets}',
        jsonb_set(coalesce(settings->'weeklyBudgets','{}'::jsonb), array[p_category], to_jsonb(round(p_amount,2)), true), true
      ), updated_at=now() where user_id=p_user_id;
    end if;
  end if;
end;
$$;
revoke all on function public.set_telegram_budget(uuid,text,numeric,text) from public, anon, authenticated;
grant execute on function public.set_telegram_budget(uuid,text,numeric,text) to service_role;

create or replace function public.consume_telegram_rate_limit(p_chat_id text, p_limit integer default 25)
returns boolean language plpgsql security definer set search_path = '' as $$
declare v_count integer;
begin
  insert into public.telegram_rate_limits(telegram_chat_id, window_started_at, message_count)
  values (p_chat_id, now(), 1)
  on conflict (telegram_chat_id) do update set
    window_started_at = case when telegram_rate_limits.window_started_at < now() - interval '1 minute' then now() else telegram_rate_limits.window_started_at end,
    message_count = case when telegram_rate_limits.window_started_at < now() - interval '1 minute' then 1 else telegram_rate_limits.message_count + 1 end
  returning message_count into v_count;
  return v_count <= greatest(1, least(p_limit, 60));
end;
$$;
revoke all on function public.consume_telegram_rate_limit(text,integer) from public, anon, authenticated;
grant execute on function public.consume_telegram_rate_limit(text,integer) to service_role;
